version: "3.9"

services:
  vllm_qwen3_tts:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/vllm/vllm-omni:v0.14.0
    runtime: nvidia
    container_name: vllm-qwen3-tts
    # environment:
    #   - HF_HOME=/root/.cache/huggingface
    volumes:
      - /media/llm:/media/llm
    ipc: host
    ports:
      - "9131:8091"
    command:
      [
        "vllm", "serve", "/media/llm/Qwen/Qwen3-TTS-12Hz-1.7B-CustomVoice",
        "--omni",
        "--stage-configs-path", "vllm_omni/model_executor/stage_configs/qwen3_tts.yaml",
        "--host", "0.0.0.0",
        "--port", "8091",
        "--served-model-name", "Qwen3-TTS-12Hz-1.7B-CustomVoice",
        "--gpu-memory-utilization", "0.9",
        "--trust-remote-code",
        # "--max-num-seqs", "4",
        # "--max-num-batched-tokens", "4096",
        # "--compilation-config", "{\"mode\": 3, \"cudagraph_capture_sizes\": [1, 2, 4]}",
        # "--enable-request-id-headers",
        "--enable-cache-dit-summary"
      ]
    restart: always
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                capabilities: [gpu]
                device_ids: [ "6" ]