version: '3'
services:
  m3e_api:
    image: model.vnet.com/sjhl/m3e-api:latest
    container_name: m3e-api-cpu
    environment:
      TZ: Asia/Shanghai
      # sk-key: sk-123456
      sk-key: "sk-aaabbbcccdddeeefffggghhhiiijjjkkk"
    restart: always
    networks:
      - m3e-api
    ports:
      - "6008:6008"

networks:
  m3e-api:
    driver: bridge

