#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/defaults.env"

# -----------------------------
# 配置变量（可通过环境变量覆盖，见 Makefile / ufw.sh help）
# -----------------------------
if [[ -z "${TARGET_PORTS+x}" ]]; then
    TARGET_PORTS="$UFW_DEFAULT_TARGET_PORTS"
fi
# 支持逗号分隔，与 WHITELIST_IPS 一致
TARGET_PORTS="${TARGET_PORTS//,/ }"

# 未设置时用默认值；显式传空字符串视为空（WHITELIST_IPS 在 enable 时不能为空）
parse_list_env() {
    # 将 "a,b c d" 解析到名为 $2 的 bash 数组
    local raw="${1//,/ }"
    local -n _parse_dest="$2"
    read -ra _parse_dest <<< "$raw"
}

if [[ -z "${WHITELIST_IPS+x}" ]]; then
    parse_list_env "$UFW_DEFAULT_WHITELIST" WHITELIST_IPS
else
    parse_list_env "$WHITELIST_IPS" WHITELIST_IPS
fi
if [[ -z "${INTERNAL_CIDRS+x}" ]]; then
    parse_list_env "${UFW_INTERNAL_CIDRS:-}" INTERNAL_CIDRS
else
    parse_list_env "$INTERNAL_CIDRS" INTERNAL_CIDRS
fi
unset UFW_DEFAULT_TARGET_PORTS UFW_DEFAULT_WHITELIST UFW_INTERNAL_CIDRS

# 自动检测默认出口网卡（用于区分外网入站 vs 容器出站）
EXTERNAL_INTERFACE="${EXTERNAL_INTERFACE:-$(ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="dev"){print $(i+1); exit}}')}"

# Docker 重启后恢复 DOCKER-USER（UFW 规则会持久化，DOCKER-USER 不会）
STATE_FILE="${UFW_DOCKER_USER_STATE:-/etc/ufw/docker-user.env}"
HOOK_BIN="${UFW_DOCKER_USER_BIN:-/usr/local/sbin/ufw-docker-user}"
HOOK_DROPIN="${UFW_DOCKER_USER_DROPIN:-/etc/systemd/system/docker.service.d/ufw-docker-user.conf}"

# -----------------------------
# 通配符 / CIDR 归一化
# -----------------------------
to_cidr() {
    local entry="$1"
    if [[ "$entry" == */* ]]; then
        echo "$entry"
        return
    fi
    if [[ "$entry" != *"*"* ]]; then
        echo "$entry"
        return
    fi
    local a b c d
    IFS='.' read -r a b c d <<< "$entry"
    [[ -z "$a" || "$a" == "*" ]] && { echo "错误：无效白名单条目 $entry" >&2; return 1; }
    if   [[ "$b" == "*" ]]; then echo "${a}.0.0.0/8"
    elif [[ "$c" == "*" ]]; then echo "${a}.${b}.0.0/16"
    elif [[ "$d" == "*" ]]; then echo "${a}.${b}.${c}.0/24"
    else                          echo "${a}.${b}.${c}.${d}/32"
    fi
}

is_ipv4_cidr() {
    [[ "$1" != *:* && "$1" =~ ^[0-9] ]]
}

is_ipv6_cidr() {
    [[ "$1" == *:* ]]
}

# 判断 IP 是否落在白名单 CIDR 内（需 python3）
ip_in_cidr() {
    local ip="$1" cidr="$2"
    python3 - "$ip" "$cidr" <<'PY'
import ipaddress, sys
ip, cidr = sys.argv[1], sys.argv[2]
try:
    addr = ipaddress.ip_address(ip)
    net = ipaddress.ip_network(cidr, strict=False)
    sys.exit(0 if addr in net else 1)
except ValueError:
    sys.exit(1)
PY
}

# TARGET_PORTS / WHITELIST_IPS 不能为空
validate_config() {
    local port ip has_port=false has_ip=false

    for port in ${TARGET_PORTS//,/ }; do
        [[ -n "$port" ]] && has_port=true && break
    done
    if ! $has_port; then
        echo "错误：TARGET_PORTS 不能为空，请至少指定一个端口" >&2
        exit 1
    fi

    for ip in "${WHITELIST_IPS[@]}"; do
        [[ -n "$ip" ]] && has_ip=true && break
    done
    if ! $has_ip; then
        echo "错误：WHITELIST_IPS 不能为空，请至少指定一个 IP 或网段" >&2
        exit 1
    fi
}

# SSH 会话来源 IP 必须在内网网段或公网白名单内，避免误配锁死
assert_ssh_whitelisted() {
    [[ -z "${SSH_CONNECTION:-}" ]] && return 0
    local ssh_ip="${SSH_CONNECTION%% *}"
    local ip cidr
    for ip in "${INTERNAL_CIDRS[@]}" "${WHITELIST_IPS[@]}"; do
        [[ -n "$ip" ]] || continue
        cidr=$(to_cidr "$ip") || return 1
        if ip_in_cidr "$ssh_ip" "$cidr"; then
            echo "SSH 来源 ${ssh_ip} 在允许范围内（${cidr}）"
            return 0
        fi
    done
    echo "错误：当前 SSH 来源 ${ssh_ip} 不在内网网段或公网白名单，拒绝应用规则以免锁死连接" >&2
    echo "请先将 ${ssh_ip} 加入 INTERNAL_CIDRS 或 WHITELIST_IPS 后再运行" >&2
    exit 1
}

ensure_forward_policy() {
    local ufw_default="/etc/default/ufw"
    if grep -q 'DEFAULT_FORWARD_POLICY="ACCEPT"' "$ufw_default"; then
        return 0
    fi
    if grep -q 'DEFAULT_FORWARD_POLICY="DROP"' "$ufw_default"; then
        sudo sed -i 's/DEFAULT_FORWARD_POLICY="DROP"/DEFAULT_FORWARD_POLICY="ACCEPT"/' "$ufw_default"
        echo "已将 DEFAULT_FORWARD_POLICY 设为 ACCEPT（Docker 转发需要）"
        return 0
    fi
    echo "警告：无法在 ${ufw_default} 中设置 DEFAULT_FORWARD_POLICY=ACCEPT，Docker 转发可能异常" >&2
}

save_docker_user_state() {
    local tmp
    tmp="$(mktemp)"
    {
        echo "# generated by tools/ufw/ufw.sh enable — used by docker-user hook"
        printf 'EXTERNAL_INTERFACE=%q\n' "$EXTERNAL_INTERFACE"
        printf 'TARGET_PORTS=%q\n' "$TARGET_PORTS"
        printf 'WHITELIST_IPS=%q\n' "${WHITELIST_IPS[*]}"
        printf 'INTERNAL_CIDRS=%q\n' "${INTERNAL_CIDRS[*]}"
    } > "$tmp"
    sudo install -d -m 755 /etc/ufw
    sudo install -m 644 -o root -g root "$tmp" "$STATE_FILE"
    rm -f "$tmp"
    echo "已保存 DOCKER-USER 配置: $STATE_FILE"
}

load_docker_user_state() {
    if [[ ! -f "$STATE_FILE" ]]; then
        echo "错误：缺少 ${STATE_FILE}，请先 make enable / make h20-43 / make h20-44" >&2
        exit 1
    fi
    echo "加载上次 enable 配置: $STATE_FILE"
    # shellcheck disable=SC1090
    source "$STATE_FILE"
    parse_list_env "$WHITELIST_IPS" WHITELIST_IPS
    parse_list_env "${INTERNAL_CIDRS:-}" INTERNAL_CIDRS
    TARGET_PORTS="${TARGET_PORTS//,/ }"
}

has_systemd() {
    command -v systemctl >/dev/null 2>&1 && [[ -d /run/systemd/system ]]
}

install_docker_hook() {
    sudo tee "$HOOK_BIN" >/dev/null <<EOF
#!/bin/bash
# generated by tools/ufw — restore DOCKER-USER after docker start
exec "${SCRIPT_DIR}/ufw.sh" docker-user
EOF
    sudo chmod 755 "$HOOK_BIN"
    if ! has_systemd; then
        echo "警告：无 systemd，已写 ${HOOK_BIN}，但 Docker 重启后不会自动恢复 DOCKER-USER" >&2
        return 0
    fi
    sudo install -d -m 755 "$(dirname "$HOOK_DROPIN")"
    sudo tee "$HOOK_DROPIN" >/dev/null <<EOF
# generated by tools/ufw — restore DOCKER-USER after docker start
[Service]
ExecStartPost=-${HOOK_BIN}
EOF
    sudo systemctl daemon-reload
    echo "已安装 Docker 启动钩子: $HOOK_DROPIN → $HOOK_BIN"
}

uninstall_docker_hook() {
    sudo rm -f "$HOOK_DROPIN" "$HOOK_BIN"
    if has_systemd; then
        sudo systemctl daemon-reload
    fi
    echo "已移除 Docker 启动钩子"
}

DOCKER_USER_LOG_PREFIX="[DOCKER-USER DROP] "
DOCKER_USER_LOG_LIMIT="${DOCKER_USER_LOG_LIMIT:-30/min}"
DOCKER_USER_LOG_BURST="${DOCKER_USER_LOG_BURST:-50}"

# DOCKER-USER：LOG（限速）+ DROP，拦截记录写入 /var/log/kern.log
docker_user_drop_with_log() {
    local ipt="$1"
    shift
    sudo "$ipt" -A DOCKER-USER "$@" \
        -m limit --limit "$DOCKER_USER_LOG_LIMIT" --limit-burst "$DOCKER_USER_LOG_BURST" \
        -j LOG --log-prefix "$DOCKER_USER_LOG_PREFIX" --log-level 4
    sudo "$ipt" -A DOCKER-USER "$@" -j DROP
}

# -----------------------------
# 配置 iptables/ip6tables 的 DOCKER-USER 链
# -----------------------------
configure_docker_user_chain() {
    local ipt="$1"  # iptables 或 ip6tables
    local is_v6=false
    [[ "$ipt" == "ip6tables" ]] && is_v6=true

    if ! sudo "$ipt" -L DOCKER-USER -n &>/dev/null; then
        echo "警告：$ipt DOCKER-USER 链不存在（Docker 未运行？），跳过" >&2
        echo "      Docker 启动后请重新执行: $0 enable" >&2
        return 0
    fi

    sudo "$ipt" -F DOCKER-USER
    sudo "$ipt" -A DOCKER-USER -m conntrack --ctstate RELATED,ESTABLISHED -j RETURN

    # 仅放行「从网桥进来」的 FORWARD（容器出网 / 容器互访）。
    # 禁止 -o docker0/br-+ RETURN：外网访问 ports: 映射的路径是 in=外网卡 out=br-*，
    # 若 -o 放行会绕过下方白名单，把容器端口暴露到公网。
    sudo "$ipt" -A DOCKER-USER -i docker0 -j RETURN
    sudo "$ipt" -A DOCKER-USER -i br-+ -j RETURN

    # 内网 RFC1918：外网卡入站全端口放行（不限 TCP/UDP）
    local ip cidr
    for ip in "${INTERNAL_CIDRS[@]}"; do
        [[ -n "$ip" ]] || continue
        cidr=$(to_cidr "$ip") || return 1
        if $is_v6; then
            is_ipv6_cidr "$cidr" || continue
        else
            is_ipv4_cidr "$cidr" || continue
        fi
        sudo "$ipt" -A DOCKER-USER -i "$EXTERNAL_INTERFACE" -s "$cidr" -j RETURN
    done

    local port has_v6_rule=false
    for port in $TARGET_PORTS; do
        for ip in "${WHITELIST_IPS[@]}"; do
            cidr=$(to_cidr "$ip") || return 1
            if $is_v6; then
                is_ipv6_cidr "$cidr" || continue
                has_v6_rule=true
            else
                is_ipv4_cidr "$cidr" || continue
            fi
            sudo "$ipt" -A DOCKER-USER -i "$EXTERNAL_INTERFACE" -p tcp \
                -m conntrack --ctorigdstport "$port" -s "$cidr" -j ACCEPT
        done
    done

    # 统一 DROP 外网入站 TCP/UDP（白名单 TCP 已在上方 ACCEPT；内网已 RETURN）
    docker_user_drop_with_log "$ipt" -i "$EXTERNAL_INTERFACE" -p tcp \
        -m conntrack --ctorigdstport 1:65535
    docker_user_drop_with_log "$ipt" -i "$EXTERNAL_INTERFACE" -p udp \
        -m conntrack --ctorigdstport 1:65535

    sudo "$ipt" -A DOCKER-USER -j RETURN

    if $is_v6 && ! $has_v6_rule; then
        echo "$ipt DOCKER-USER 已配置（无 IPv6 白名单，外网 IPv6 访问 Docker 端口将被拒绝；DROP 写入 kern.log）"
    else
        echo "$ipt DOCKER-USER 已配置（DROP 写入 kern.log，make log 查看）"
    fi
}

# Docker 网桥 → 宿主机 INPUT：host 网络与 bridge（host.docker.internal）都放行
# br-+ 通配 enable 之后新建的 compose 网桥（原先只写死当时已有的 br-xxx，新网桥会被 deny incoming 丢掉）
allow_docker_bridges() {
    echo "允许 Docker 网桥与宿主机互通（docker0 + br-* 通配）"
    local spec
    for spec in docker0 br-+; do
        echo "  UFW: allow in/out on $spec"
        sudo ufw allow in  on "$spec" comment 'docker-bridge-host'
        sudo ufw allow out on "$spec" comment 'docker-bridge-host'
    done
}

# 不 reset UFW：补 -i 网桥 RETURN；若存在会绕过白名单的 -o 规则则删除
ensure_docker_user_bridge_return() {
    local ipt="$1"
    if ! sudo "$ipt" -L DOCKER-USER -n &>/dev/null; then
        echo "警告：$ipt DOCKER-USER 链不存在，跳过网桥 RETURN" >&2
        return 0
    fi
    local spec
    for spec in docker0 br-+; do
        while sudo "$ipt" -C DOCKER-USER -o "$spec" -j RETURN 2>/dev/null; do
            sudo "$ipt" -D DOCKER-USER -o "$spec" -j RETURN
            echo "  $ipt DOCKER-USER: 已删除 RETURN -o $spec（避免绕过白名单）"
        done
        if sudo "$ipt" -C DOCKER-USER -i "$spec" -j RETURN 2>/dev/null; then
            continue
        fi
        sudo "$ipt" -I DOCKER-USER 2 -i "$spec" -j RETURN
        echo "  $ipt DOCKER-USER: RETURN -i $spec"
    done
}

cmd_docker_bridges() {
    echo "补齐 Docker 网桥规则（不重置 UFW / 不改白名单）"
    allow_docker_bridges
    if [[ -f "$STATE_FILE" ]]; then
        echo "检测到 ${STATE_FILE}，同时恢复完整 DOCKER-USER 拦截规则"
        cmd_docker_user
        echo "完成：网桥 + DOCKER-USER 已恢复"
        return 0
    fi
    ensure_docker_user_bridge_return "iptables"
    ensure_docker_user_bridge_return "ip6tables"
    echo "完成：host 网络与网桥（host.docker.internal）均可访问宿主机端口"
    echo "提示：完整公网拦截需先 make enable，之后 Docker 重启会自动恢复"
}

wait_docker_user_chain() {
    local ipt="$1" i
    for i in $(seq 1 30); do
        if sudo "$ipt" -L DOCKER-USER -n &>/dev/null; then
            return 0
        fi
        sleep 0.5
    done
    return 1
}

apply_docker_user_chains() {
    local ipt
    for ipt in iptables ip6tables; do
        if ! sudo "$ipt" -L DOCKER-USER -n &>/dev/null; then
            echo "等待 ${ipt} DOCKER-USER 链..."
            if ! wait_docker_user_chain "$ipt"; then
                echo "警告：${ipt} DOCKER-USER 链不存在（Docker 未运行？），跳过" >&2
                continue
            fi
        fi
        configure_docker_user_chain "$ipt"
    done
}

cmd_docker_user() {
    load_docker_user_state
    validate_config
    if [[ -z "$EXTERNAL_INTERFACE" ]]; then
        echo "错误：状态文件中无 EXTERNAL_INTERFACE" >&2
        exit 1
    fi
    echo "出口网卡：$EXTERNAL_INTERFACE"
    echo "TARGET_PORTS=$TARGET_PORTS"
    echo "WHITELIST_IPS=${WHITELIST_IPS[*]}"
    echo "INTERNAL_CIDRS=${INTERNAL_CIDRS[*]}"
    apply_docker_user_chains
}

cmd_install_hook() {
    install_docker_hook
    if [[ -f "$STATE_FILE" ]]; then
        cmd_docker_user
    else
        echo "提示：尚无 ${STATE_FILE}，请先 make enable / make h20-43 才会在 Docker 重启后恢复拦截"
    fi
}

cmd_enable() {
    validate_config

    if [[ -z "$EXTERNAL_INTERFACE" ]]; then
        echo "错误：无法自动检测出口网卡，请设置 EXTERNAL_INTERFACE 环境变量" >&2
        exit 1
    fi
    echo "出口网卡：$EXTERNAL_INTERFACE"

    assert_ssh_whitelisted

    echo "重置 UFW..."
    sudo ufw --force reset

    ensure_forward_policy

    echo "设置默认策略：拒绝入站，出站与转发不受限"
    sudo ufw default deny incoming
    sudo ufw default allow outgoing
    sudo ufw default allow routed

    echo "允许 Docker 网桥内部流量..."
    allow_docker_bridges

    echo "允许内网网段全端口入站（INTERNAL_CIDRS）..."
    local ip cidr
    for ip in "${INTERNAL_CIDRS[@]}"; do
        [[ -n "$ip" ]] || continue
        cidr=$(to_cidr "$ip") || exit 1
        echo "  UFW: allow from $cidr"
        sudo ufw allow from "$cidr" comment 'rfc1918-internal'
    done

    echo "配置 UFW 公网白名单规则（TARGET_PORTS）..."
    local port ip cidr
    for port in $TARGET_PORTS; do
        for ip in "${WHITELIST_IPS[@]}"; do
            cidr=$(to_cidr "$ip") || exit 1
            if is_ipv4_cidr "$cidr"; then
                sudo ufw allow from "$cidr" to any port "$port" proto tcp
            elif is_ipv6_cidr "$cidr"; then
                sudo ufw allow from "$cidr" to any port "$port" proto tcp
            fi
        done
    done

    echo "启用 UFW..."
    sudo ufw --force enable

    configure_docker_user_chain "iptables"
    configure_docker_user_chain "ip6tables"

    save_docker_user_state
    install_docker_hook

    echo ""
    echo "完成！"
    echo "  - 内网（${INTERNAL_CIDRS[*]:-无}）：全端口放行"
    echo "  - TARGET_PORTS（${TARGET_PORTS}）：仅公网白名单可访问"
    echo "  - 其余公网入站 TCP/UDP：拒绝"
    echo "  - 本机与容器访问公网：不受限制"
    echo "  - Docker 网桥（docker0 / br-*）：与宿主机互通，host 网络与 host.docker.internal 均可用"
    echo "  - Docker 重启后由 ${HOOK_BIN} 自动恢复 DOCKER-USER"
    echo ""
    sudo ufw status verbose
    echo ""
    echo "=== iptables DOCKER-USER ==="
    sudo iptables  -L DOCKER-USER -n --line-numbers 2>/dev/null || echo "（链不存在）"
    echo ""
    echo "=== ip6tables DOCKER-USER ==="
    sudo ip6tables -L DOCKER-USER -n --line-numbers 2>/dev/null || echo "（链不存在）"
}

cmd_disable() {
    echo "关闭 UFW..."
    sudo ufw disable

    local ipt
    for ipt in iptables ip6tables; do
        if sudo "$ipt" -L DOCKER-USER -n &>/dev/null; then
            echo "清空 ${ipt} DOCKER-USER 链，恢复 Docker 默认放行"
            sudo "$ipt" -F DOCKER-USER
            sudo "$ipt" -A DOCKER-USER -j RETURN
        fi
    done

    uninstall_docker_hook
    sudo rm -f "$STATE_FILE"

    echo "完成：UFW 已关闭，DOCKER-USER 已恢复为默认 RETURN，启动钩子已移除"
    sudo ufw status 2>/dev/null || true
}

grep_docker_drop_logs() {
    local f=/var/log/kern.log
    {
        if [[ -f "$f" ]]; then
            sudo grep -hF "$DOCKER_USER_LOG_PREFIX" "$f" 2>/dev/null || true
        fi
        for rot in "$f".* "$f"-*; do
            [[ -e "$rot" ]] || continue
            if [[ "$rot" == *.gz ]]; then
                sudo zgrep -hF "$DOCKER_USER_LOG_PREFIX" "$rot" 2>/dev/null || true
            elif [[ -f "$rot" ]]; then
                sudo grep -hF "$DOCKER_USER_LOG_PREFIX" "$rot" 2>/dev/null || true
            fi
        done
    } | sort -u
}

format_cutoff_cst() {
    local cutoff_utc="$1"
    TZ=Asia/Shanghai date -d "${cutoff_utc} UTC" '+%Y-%m-%dT%H:%M:%S %Z' 2>/dev/null \
        || echo "${cutoff_utc} CST"
}

format_since_window() {
    local since="$1" cutoff="$2" cutoff_cst
    cutoff_cst="$(format_cutoff_cst "$cutoff")"
    if [[ "$since" =~ ^([0-9]+)[[:space:]]+days?$ ]]; then
        echo "统计窗口: 最近 ${BASH_REMATCH[1]} 天（>= ${cutoff_cst}）"
    elif [[ "$since" =~ ^([0-9]+)[[:space:]]+hours?$ ]]; then
        echo "统计窗口: 最近 ${BASH_REMATCH[1]} 小时（>= ${cutoff_cst}）"
    else
        echo "统计窗口: >= ${cutoff_cst}（BLOCKED_SINCE=${since}）"
    fi
}

# 将 BLOCKED_SINCE（如 "1 day" / "24 hours" / ISO 时间）转为可比较的 UTC 时间前缀（kern.log 为 UTC）
# ISO 无时区后缀时按中国时区（Asia/Shanghai）理解；带 Z / +00:00 / +08:00 等则按字面解析
blocked_since_cutoff() {
    local since="$1" cutoff normalized
    if [[ "$since" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2} ]]; then
        if [[ "$since" =~ [Zz]$|[+-][0-9]{2}:[0-9]{2}$ ]]; then
            if ! cutoff=$(date -u -d "$since" '+%Y-%m-%dT%H:%M:%S' 2>/dev/null); then
                echo "错误：无效的 BLOCKED_SINCE=${since}" >&2
                return 1
            fi
        else
            normalized="${since//T/ }"
            normalized="${normalized%%.*}"
            if ! cutoff=$(TZ=Asia/Shanghai date -u -d "${normalized} CST" '+%Y-%m-%dT%H:%M:%S' 2>/dev/null); then
                echo "错误：无效的 BLOCKED_SINCE=${since}（ISO 示例: 2026-06-30T17:00:00 或 2026-06-30T09:00:00+00:00）" >&2
                return 1
            fi
        fi
        echo "$cutoff"
        return 0
    fi
    if ! cutoff=$(date -u -d "$since ago" '+%Y-%m-%dT%H:%M:%S' 2>/dev/null); then
        echo "错误：无效的 BLOCKED_SINCE=${since}（示例: \"1 day\", \"24 hours\"）" >&2
        return 1
    fi
    echo "$cutoff"
}

filter_logs_since() {
    local logs="$1" since="$2"
    [[ -z "$since" ]] && { echo "$logs"; return 0; }
    local cutoff
    cutoff="$(blocked_since_cutoff "$since")" || return 1
    echo "$logs" | awk -v since="$cutoff" '
        {
            ts = $1
            sub(/\+.*$/, "", ts)
            sub(/\..*$/, "", ts)
            if (ts >= since) print
        }'
}

cmd_blocked_ips() {
    local limit="${1:-50}"
    local since="${BLOCKED_SINCE:-}"
    local logs cutoff
    logs="$(grep_docker_drop_logs)"
    if [[ -n "$since" ]]; then
        cutoff="$(blocked_since_cutoff "$since")" || exit 1
        logs="$(filter_logs_since "$logs" "$since")" || exit 1
        format_since_window "$since" "$cutoff"
        echo ""
    fi

    if [[ -z "$logs" ]]; then
        if [[ -n "$since" ]]; then
            echo "（该时间窗口内暂无拦截记录）"
        else
            echo "（暂无 LOG 记录）"
            echo "  说明：需先 make enable / make h20-43 / make h20-44 应用带 LOG 的规则，之后新的拦截才会写入 /var/log/kern.log；用 make log 查看统计"
            echo ""
            echo "=== iptables DROP 计数（历史累计，不含 IP）==="
            sudo iptables -L DOCKER-USER -n -v 2>/dev/null | grep DROP || echo "（链不存在）"
        fi
        return 0
    fi

    printf '%s\n' "$logs" | python3 "${SCRIPT_DIR}/blocked_ips_report.py"

    if [[ "$limit" != "0" ]]; then
        echo "=== 最近 ${limit} 条拦截明细 ==="
        echo "$logs" | tail -n "$limit"
    fi
}

usage() {
    cat <<EOF
用法: $0 <enable|disable|docker-user|docker-bridges|install-hook|blocked-ips [N]>

  enable         重置并应用 UFW + DOCKER-USER，并安装 Docker 启动钩子
  disable        关闭 UFW，清空 DOCKER-USER，移除启动钩子
  docker-user    仅按 ${STATE_FILE} 恢复 DOCKER-USER（不 reset UFW）
  docker-bridges 补齐网桥规则；若已 enable 则同时恢复 DOCKER-USER
  install-hook   安装 Docker 启动钩子（enable 时已自动安装）
  blocked-ips    从 kern.log 汇总 DOCKER-USER 拦截（表格；配合 BLOCKED_SINCE 过滤）
                 ISO 时间无时区时按中国时区理解，统计窗口以中国时区显示

Makefile 示例:
  make log                  最近 1 天拦截统计（表格）
  make log DAYS=3           最近 3 天
  make log BLOCKED_SINCE="24 hours"
  make enable TARGET_PORTS="22 8080" WHITELIST_IPS="1.2.3.4"
  make docker-user          # Docker 重启后手动恢复（正常已由 systemd 钩子执行）
  # 内网默认 RFC1918 全端口放行；公网仅白名单可访问 TARGET_PORTS
EOF
}

main() {
    local action="${1:-enable}"
    case "$action" in
        enable)  cmd_enable ;;
        disable) cmd_disable ;;
        docker-user) cmd_docker_user ;;
        docker-bridges) cmd_docker_bridges ;;
        install-hook) cmd_install_hook ;;
        blocked-ips|log) cmd_blocked_ips "${2:-50}" ;;
        -h|--help|help) usage ;;
        *)
            echo "错误：未知命令 $action" >&2
            usage >&2
            exit 1
            ;;
    esac
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
