version: "3.9"

services:
  vllm_qwen_image:
    image: model.vnet.com/sjhl/vllm-omni:v0.18.0
    runtime: nvidia
    container_name: vllm-qwen-image-2512
    # environment:
    #   - HF_HOME=/root/.cache/huggingface
    volumes:
      - /media/llm:/media/llm
    ipc: host
    ports:
      - "9111:8000"
    command:
      [
        "vllm", "serve", "/media/llm/Qwen/Qwen-Image-2512",
        "--omni",
        "--tensor-parallel-size", "2",  # 多卡并发数
        "--gpu-memory-utilization", "0.9",
        "--max-num-seqs", "4",
        "--max-num-batched-tokens", "8192",
        "--host", "0.0.0.0",
        "--port", "8000",
        "--served-model-name", "qwen-image",
        "--trust-remote-code",
        "--enable-request-id-headers",
        "--enable-cache-dit-summary"
      ]
              # "--compilation-config", "{\"mode\": 3, \"cudagraph_capture_sizes\": [1, 2, 4]}", 4卡优化参数
    restart: always
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                capabilities: [gpu]
                device_ids: [ "6","7" ]